
-- DO NOT EDIT - GENERATED CODE
models={
PROP_TREE1 = 1
,PROP_CHECKPOINT_LEFT = 2
,PROP_CHECKPOINT_RIGHT = 3
,PROP_TREE_SNOW = 4
,PROP_TREE0 = 5
,PROP_SNOWBALL = 6
,PROP_SPLASH = 7
,PROP_ROCK = 8
,PROP_POLE = 9
,PROP_COW = 10
,PROP_BEAR = 11
,PROP_HELO = 12
,PROP_WARNING = 13
,PROP_JUMPPAD = 14
,PROP_SHADOW = 15
,PROP_SNOWBALL_PLAYER = 16
,PROP_START = 17
,PROP_SKIER_LEFT = 18
,PROP_SKIER = 19
,PROP_SKIER_RIGHT = 20
,PROP_CABINS = 21
,PROP_BALLOON = 22
,PROP_SLED = 23

}
